
c:
	rails c
cs:
	rails c --sandbox

route:
	rails routes | grep order

m:
	rails db:migrate
mr:
	rails db:migrate:reset
md:
	rails db:migrate:down VERSION=20220416231903
ms:
	rails db:migrate:status
db:
	rails db
dbc:
	rails db:create:all
seed:
	rails db:seed

g:
	rails g model Restaurant name:string fee:integer time_required:integer
d:
	rails d model Restaurant
